### ISSUE TITLE
[Feat] 강의에 대한 좋아요 기능 추가

### ISSUE THREAD

**Issue by mobzzzzz** [one-day-one-meal/one-hour-one-meal#24]
*# 기능 설명
강의에 좋아요 기능을 추가합니다.
강의 목록 / 단건을 조회할 때 해당 강의의 좋아요 개수를 확인 가능해야 합니다.
유저가 한 강의에 한 번의 좋아요만 가능하고 이미 좋아요를 누른 유저면 좋아요를 제거합니다.
유저가 좋아요를 누른 강의 리스트만 조회도 가능합니다.

# To-do
- [ ] 강의 조회에 좋아요 개수 추가
- [ ] 한 유저가 한 강의에 한 번의 좋아요만 가능/이미 좋아요 기록이 있으면 제거
- [ ] 좋아요 누른 강의 목록만 조회 (필터링으로 구현 또는 Path 분리해 구현)

# ETC
