### ISSUE TITLE
[Feat] Spring security + JWT 인증을 통한 유저의 역할 및 id 획득

### ISSUE THREAD

**Issue by mobzzzzz** [one-day-one-meal/one-hour-one-meal#8]
*# 기능 설명
JWT Helper를 만들고 CustomAuthenticationFilter를 만들어서 Filter chain에 걸어가지고 기본적인 인증을 진행 후 SecurityUtils를 만들어서 User의 Id와 Role 에 대한 체크를 쉽게 할 수 있게 작성합니다.

# To-do
- [x] 할일 JWT Helper
- [x] 할일 CustomAuthenticationFilter를 만들어서 Filter chain에 등록 후 Swagger 예외처리
- [x] 할일 UserId와 Role을 쉽게 확인할 수 있는 SecurtyUtils 작성
- [x] 할일 Access token 기본 로직 취득 가능한 만큼 User 로직 작성
- [x] 할일 Swagger 및 H2-Console 사용에 문제 없게 설정

# ETC
